import Head from "next/head";
import { useEffect, useState } from "react";

import { useSearchKeyWords } from "contexts/SearchKeyWords";
import { findBooks } from "services/ApiFunctions/Book";

import WebsiteTemplate from "templates/Website";
import { GridContainer } from "components/GridContainer/styles";

export default function Home() {
  const [results, setResults] = useState<any>();

  const { searchKeyWords, setSearchKeyWords } = useSearchKeyWords();

  useEffect(() => {
    findBooks(searchKeyWords)
      .then(({ items }) => {
        console.log(items);
        setResults(items);
      })
      .catch((err) => console.log(err));
  }, [searchKeyWords]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WebsiteTemplate withSearchBar>
        <h2>Resultados da pesquisa:</h2>

        <GridContainer>
          {results &&
            results.map((book) => (
              <a href={`/livro/${book.id}`}>
                <li
                  key={book.id}
                  style={{
                    border: "solid 1px red",
                    borderRadius: "1rem",
                    marginBottom: "1rem",
                    padding: "1rem",
                  }}
                >
                  {book.volumeInfo?.imageLinks?.thumbnail && (
                    <img
                      src={book.volumeInfo.imageLinks.thumbnail}
                      alt="Imagem do produto"
                      width={100}
                      height={100}
                      style={{ objectFit: "contain", border: "solid 1px red" }}
                    />
                  )}
                  <h3>{book.volumeInfo.title}</h3>
                  <p>Descrição: {book.volumeInfo.description}</p>
                  <small>Data: {book.volumeInfo.publishedDate}</small>
                </li>
              </a>
            ))}
        </GridContainer>
      </WebsiteTemplate>
    </>
  );
}
