import Head from "next/head";
import { useEffect, useState } from "react";

import { useSearchKeyWords } from "contexts/SearchKeyWords";
import { findBooks } from "services/ApiFunctions/Book";

import WebsiteTemplate from "templates/Website";
import { GridContainer } from "components/GridContainer/styles";
import Card from "../components/Card";

export default function Home() {
  const [results, setResults] = useState<any>();

  const { searchKeyWords, setSearchKeyWords } = useSearchKeyWords();

  useEffect(() => {
    findBooks(searchKeyWords)
      .then(({ items }) => {
        console.log(items);
        setResults(items);
      })
      .catch((err) => console.log(err));
  }, [searchKeyWords]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WebsiteTemplate withSearchBar>
        <h2>Resultados da pesquisa:</h2>

        <GridContainer>
          {results &&
            results.map((book) => (
              <Card
                key={book.id}
                id={book.id}
                title={book.volumeInfo.title}
                imageUrl={book.volumeInfo?.imageLinks?.thumbnail}
                description={book.volumeInfo.description}
                publishedDate={book.volumeInfo.publishedDate}
              />
            ))}
        </GridContainer>
      </WebsiteTemplate>
    </>
  );
}
